import os


DATABASE_NAME = os.environ.get("DATABASE_NAME")
DATABASE_USER = os.environ.get("DATABASE_USER")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")
DATABASE_HOST = os.environ.get("DATABASE_HOST")

COGNITO_USER_POOL_ARN = os.environ.get("COGNITO_USER_POOL_ARN")
COGNITO_USER_POOL_NAME = os.environ.get("COGNITO_USER_POOL_NAME")
